swagger: '2.0'
info:
  title: "insert api"
  description: "describe api"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "applications/json"
produces:
  - "applications/json"
paths:
  /customers/login:
  post:
    tags:
      - customers
    summary: "Login endpoint, (generates token)"
    description: "Validates member credentials, generates and return a member specific token"
    parameter:
      - in: "body"
        name: "body"
        description: "Login Credentials"
        required: true
        schema:
          $ref: "#/definitions/LoginCredentials"
definitions:

  LoginCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"

    required:
      - email
      - password
  
  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
      status:
        type: "string"
      

