swagger: '2.0'
info:
  title: "insert api"
  description: "describe api"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "applications/json"
produces:
  - "applications/json"
paths:
  /customers/login:
  post:
    tags:
      - customers
    summary: "Login endpoint, (generates token)"
    description: "Validates member credentials, generates and return a member specific token"
    parameter:
      - in: "body"
        name: "body"
        description: "Login Credentials"
        required: true
        schema:
          $ref: "#/definitions/LoginCredentials"
  
  /customers: #endpoint
    post: #post request
      tags:
        - customers
      summary: "Endpointn to create/register a new customer"
      description: "Endpoint to create a new customer in our mechanic shop"
      parameters:
        - in: "body"
          name: "body"
          description: "Information required to create a new member"
          required: true
          schema:
            $ref: "#/definitions/CreateMemberPayload"
      responses:
        201:
          descriptions: "Successful member creation"
          schema: 
            $ref: "#/definitions/CreateMemberResponse"
          examples:
            application/json:
              id: 1
              name: John Doe
              phone: 1111111111
              email: john@test.com
              password: john123

definitions:

  LoginCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"

    required:
      - email
      - password
  
  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
      status:
        type: "string"

  CreateMemberPayload:
    type: "object"
    properties:
      name:
        type: "string"
      email: 
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"

    required:
      - name
      - email
      - phone 
      - password

  CreateMemberResponse:
    type: "object"
    properties:
      id: 
        type: 'int'
      name:
        type: 'string'
      email: 
        type: 'string'
      phone: 
        type: 'string'
      password:
        type: 'string'

