swagger: '2.0'
info:
  title: "insert api"
  description: "describe api"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "applications/json"
produces:
  - "applications/json"
paths:
definitions: